### ISSUE TITLE
FIX: Notebook server no longer allow upload

### ISSUE THREAD

**Issue by roachmd** [3Blades/notebook-servers#41]
With Backend Build 702
Notebooks:
3blades/datascience-notebook   latest                     7 days ago          9.95GB
3blades/rstudio                latest                     7 days ago          1.07GB

## Notebook server no longer allows upload. UI Seem to work fine.
 ** Note this works with Build 685

**Comment by johngriebel** [comment]
@roachmd the latest docker builds for both of those images are from yesterday. Are you sure you hade the latest images?
